-- MySQL Script generated by MySQL Workbench
-- jue 11 oct 2018 23:47:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema group152
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `group152` ;

-- -----------------------------------------------------
-- Schema group152
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `group152` DEFAULT CHARACTER SET utf8 ;
USE `group152` ;

-- -----------------------------------------------------
-- Table `group152`.`pasajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`pasajero` ;

CREATE TABLE IF NOT EXISTS `group152`.`pasajero` (
  `id_pasajero` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `apellido` VARCHAR(30) NULL,
  `email` VARCHAR(50) NULL,
  `salt` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `id_pasajero_UNIQUE` (`id_pasajero` ASC),
  PRIMARY KEY (`id_pasajero`, `dni`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  UNIQUE INDEX `salt_UNIQUE` (`salt` ASC),
  UNIQUE INDEX `password_hash_UNIQUE` (`password_hash` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group152`.`parada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`parada` ;

CREATE TABLE IF NOT EXISTS `group152`.`parada` (
  `id_parada` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `numero` VARCHAR(8) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_parada`),
  UNIQUE INDEX `id_parada_UNIQUE` (`id_parada` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group152`.`viaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`viaje` ;

CREATE TABLE IF NOT EXISTS `group152`.`viaje` (
  `id_viaje` INT NOT NULL AUTO_INCREMENT,
  `destino` VARCHAR(45) NULL,
  `origen` VARCHAR(45) NULL,
  PRIMARY KEY (`id_viaje`),
  UNIQUE INDEX `id_viaje_UNIQUE` (`id_viaje` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group152`.`pasaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`pasaje` ;

CREATE TABLE IF NOT EXISTS `group152`.`pasaje` (
  `id_pasaje` INT NOT NULL AUTO_INCREMENT,
  `horario` TIME NULL,
  `pasajero_id_pasajero` INT NOT NULL,
  `pasajero_dni` VARCHAR(10) NOT NULL,
  `parada_id_parada` INT NOT NULL,
  `viaje_id_viaje` INT NOT NULL,
  PRIMARY KEY (`id_pasaje`),
  UNIQUE INDEX `id_pasaje_UNIQUE` (`id_pasaje` ASC),
  INDEX `fk_pasaje_pasajero_idx` (`pasajero_id_pasajero` ASC, `pasajero_dni` ASC),
  INDEX `fk_pasaje_parada1_idx` (`parada_id_parada` ASC),
  INDEX `fk_pasaje_viaje1_idx` (`viaje_id_viaje` ASC),
  CONSTRAINT `fk_pasaje_pasajero`
    FOREIGN KEY (`pasajero_id_pasajero` , `pasajero_dni`)
    REFERENCES `group152`.`pasajero` (`id_pasajero` , `dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasaje_parada1`
    FOREIGN KEY (`parada_id_parada`)
    REFERENCES `group152`.`parada` (`id_parada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasaje_viaje1`
    FOREIGN KEY (`viaje_id_viaje`)
    REFERENCES `group152`.`viaje` (`id_viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group152`.`combi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`combi` ;

CREATE TABLE IF NOT EXISTS `group152`.`combi` (
  `id_combi` INT NOT NULL AUTO_INCREMENT,
  `patente` VARCHAR(7) NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `asientos` INT NULL,
  PRIMARY KEY (`id_combi`, `patente`),
  UNIQUE INDEX `patente_UNIQUE` (`patente` ASC),
  UNIQUE INDEX `id_combi_UNIQUE` (`id_combi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group152`.`combi_has_parada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`combi_has_parada` ;

CREATE TABLE IF NOT EXISTS `group152`.`combi_has_parada` (
  `combi_id_combi` INT NOT NULL,
  `combi_patente` VARCHAR(7) NOT NULL,
  `parada_id_parada` INT NOT NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`combi_id_combi`, `combi_patente`, `parada_id_parada`),
  INDEX `fk_combi_has_parada_parada1_idx` (`parada_id_parada` ASC),
  INDEX `fk_combi_has_parada_combi1_idx` (`combi_id_combi` ASC, `combi_patente` ASC),
  CONSTRAINT `fk_combi_has_parada_combi1`
    FOREIGN KEY (`combi_id_combi` , `combi_patente`)
    REFERENCES `group152`.`combi` (`id_combi` , `patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combi_has_parada_parada1`
    FOREIGN KEY (`parada_id_parada`)
    REFERENCES `group152`.`parada` (`id_parada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group152`.`combi_has_viaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group152`.`combi_has_viaje` ;

CREATE TABLE IF NOT EXISTS `group152`.`combi_has_viaje` (
  `combi_id_combi` INT NOT NULL,
  `combi_patente` VARCHAR(7) NOT NULL,
  `viaje_id_viaje` INT NOT NULL,
  PRIMARY KEY (`combi_id_combi`, `combi_patente`, `viaje_id_viaje`),
  INDEX `fk_combi_has_viaje_viaje1_idx` (`viaje_id_viaje` ASC),
  INDEX `fk_combi_has_viaje_combi1_idx` (`combi_id_combi` ASC, `combi_patente` ASC),
  CONSTRAINT `fk_combi_has_viaje_combi1`
    FOREIGN KEY (`combi_id_combi` , `combi_patente`)
    REFERENCES `group152`.`combi` (`id_combi` , `patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combi_has_viaje_viaje1`
    FOREIGN KEY (`viaje_id_viaje`)
    REFERENCES `group152`.`viaje` (`id_viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
